name: Expire Subscriptions

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  call-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call expiry endpoint
        run: |
          curl -X POST \
          https://incredible-nonie-bmsconcept-37359733.koyeb.app/internal/cron/expire-subscriptions \
          -H "X-Admin-Key: ${{ secrets.ADMIN_API_KEY }}"
